"""Generate docs/TRACEABILITY.md — a requirements traceability matrix built from the last full run."""
import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
reqs = json.loads((ROOT / "docs" / "requirements.json").read_text())
results = json.loads((ROOT / "reports" / "results.json").read_text())
manual = json.loads((ROOT / "docs" / "manual_and_static.json").read_text())["manual_cases"]
LEVELS = ["Unit", "Integration", "System", "System (E2E UI)", "Acceptance (UAT)"]
SHORT = {"System (E2E UI)": "E2E", "Acceptance (UAT)": "UAT"}
ORDER = [r["id"] for r in reqs]


def expand(field: str) -> list[str]:
    """'FR-01..FR-09' and 'FR-03, FR-10' style references → individual requirement IDs."""
    out = []
    for part in [p.strip() for p in field.split(",")]:
        m = re.fullmatch(r"(FR)-(\d+)\.\.FR-(\d+)", part)
        if m:
            out += [f"FR-{i:02d}" for i in range(int(m.group(2)), int(m.group(3)) + 1)]
        elif part:
            out.append(part)
    return [o for o in out if o in ORDER]


cells = defaultdict(lambda: defaultdict(int))
passed, ids = defaultdict(int), defaultdict(list)
for r in results:
    for q in expand(r["requirement"]):
        cells[q][r["level"]] += 1
        passed[q] += r["status"] == "PASS"
        ids[q].append(r["id"])
man = defaultdict(list)
for m in manual:
    for q in expand(m["requirement"]):
        man[q].append(f'{m["id"].replace("TC-MAN-", "")} ({m.get("status", "")})')

lines = ["# Requirements traceability matrix", "",
         f"Generated by `tools/make_traceability.py` from `reports/results.json` ({len(results)} automated test cases) and "
         "`docs/manual_and_static.json`. A case that names a requirement range (e.g. `FR-01..FR-09`) counts for every "
         "requirement in it.", "",
         "| Requirement | Area | Priority | " + " | ".join(SHORT.get(lv, lv) for lv in LEVELS) + " | Automated | Passed | Manual | Status |",
         "|---|---|---|" + "---:|" * len(LEVELS) + "---:|---:|---|---|"]
covered = 0
for r in reqs:
    q = r["id"]
    total = sum(cells[q].values())
    covered += total > 0
    skipped = total - passed[q]
    status = "✅ covered" if total and not skipped else ("⚠️ partial (skipped cases)" if total else "❌ no tests")
    lines.append(f"| **{q}** | {r['area']} | {r['priority']} | " + " | ".join(str(cells[q][lv] or "·") for lv in LEVELS)
                 + f" | {total} | {passed[q]} | {', '.join(man[q]) or '·'} | {status} |")
lines += ["", f"**{covered} / {len(reqs)} requirements** have at least one executed automated test case.", "",
          "## Requirement text", "", "| ID | Requirement |", "|---|---|"]
lines += [f"| {r['id']} | {r['text']} |" for r in reqs]
(ROOT / "docs" / "TRACEABILITY.md").write_text("\n".join(lines) + "\n")
print(f"wrote docs/TRACEABILITY.md — {covered}/{len(reqs)} requirements covered")
